version: "3.7"
services:
  finance-web:
    image: DOCKER_IMAGE
    container_name: CONTAINER_NAME
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 80
    networks:
      - nginxproxymanager_default

networks:
  nginxproxymanager_default:
    external: true