@Library('2code-jenkins@main')
import br.com.twocode.Commands
import br.com.twocode.ProjectMetadata
 
def projectMetadata = new ProjectMetadata();
def cmd = new Commands();

projectMetadata.projectName = "finance-flutter-web"
projectMetadata.dockerfile = "Dockerfile"
projectMetadata.language = "financeFlutterWeb"
projectMetadata.version = "1.0"

cmd.exec(projectMetadata);